### ISSUE TITLE
example missing in 2022/19

### ISSUE THREAD

**Issue by wimglenn** [mjpieters/adventofcode#29]
Nice notebooks this year, Martijn! I noticed the assert in [Day 19.ipynb](https://github.com/mjpieters/adventofcode/blob/master/2022/Day%2019.ipynb) part 2 is bogus:

    assert reduce(mul, largest_number_geodes(example))

It should be 

    assert reduce(mul, largest_number_geodes(example)) == 3472

Or even better

    assert math.prod(largest_number_geodes(example)) == 3472

**Comment by mjpieters** [comment]
Ah, well spotted! I've fixed it in the simplest way possible; I wasn't yet aware of math.prod at the time.
