### ISSUE TITLE
2020 day 1 bug

### ISSUE THREAD

**Issue by wimglenn** [mjpieters/adventofcode#7]
This algorithm made assumption that half the target is not in the set. Example, with input coins:

```
1010
786
1234
```

It's needed to find the `786*1234` solution and not `1010*1010`. Probably better to use a multiset (`collections.Counter`).

**Comment by mjpieters** [comment]
I can't say I care that much. I'd not use a counter either, a check that the two numbers differ would do.

**Comment by wimglenn** [comment]
@mjpieters Nope, a check that two numbers differ is insufficient. The code would then fail to find the solution for an input such as:

    1010
    700
    1234 
    1010

**Comment by mjpieters** [comment]
Right, but my input data only contains unique entries. I’m not really that interested in ensuring the code here works tor every possible input dataset.
